---

marp_theme: example
marp_backgroundColor: #ffffff
marp_backgroundImage: 'example/images/slide-background.png'
marp_author: 'Raoul Scarazzini'
marp_copyright: '© 2023 MiaMammaUsaLinux.org'
marp_paginate: true

marp_cover_template: 'example/templates/cover.md.j2'
marp_cover_image: 'example/images/cover-image.png'
marp_cover_logo: 'example/images/logo.png'
marp_cover_backgroundImage: 'example/images/cover-background.png'

marp_chapter_template: 'example/templates/chapter.md.j2'
marp_chapter_backgroundImage: 'example/images/chapter-background.png'
