---

- name: KPA project markdown files generation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import KPA Marp slides generator role
      ansible.builtin.import_role:
        name: mmul.kpa_marp_slides_generator
