name: Linter, test, build and push KPA container

env:
  KPA_PROJECT: example
  REGISTRY_NAME: ghcr.io
  CONTAINER_NAME: mmul-it/kpa
  CONTAINER_VERSION: latest

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mmul-it/kpa-marp-pandoc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible requirements
        run: ansible-galaxy install
               -r playbooks/roles/requirements.yml
               --roles-path ./playbooks/roles
      - name: Check Ansible Playbook Linter
        run: ansible-lint playbooks/*.yml
      - name: Check project yamls
        run: yamllint -s projects/${KPA_PROJECT}/*.yml
      - name: Check markdown files for example project
        run: mdl projects/${KPA_PROJECT}/contents/*.md

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mmul-it/kpa-marp-pandoc
    needs: linter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Ansible requirements
        run: ansible-galaxy install
               -r playbooks/roles/requirements.yml
               --roles-path ./playbooks/roles
      - name: Generate markdown and pdf files
        run: for KPA_DOC in $(ls projects/${KPA_PROJECT}/*.yml); do
               echo "Processing ${TRAINING}";
               ansible-playbook
                 -e @projects/${KPA_PROJECT}/common/settings.yml
                 -e @${KPA_DOC}
                 playbooks/kpa_generator.yml;
             done
      - name: Upload generated markdown files
        uses: actions/upload-artifact@v3
        with:
          name: markdowns
          path: output/**.md
      - name: Upload generated pdf files
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: output/**.pdf

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Build the container image
      run: docker build . --file Dockerfile --tag ${REGISTRY_NAME}/${CONTAINER_NAME}:${CONTAINER_VERSION}
    - name: Login into the container registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ vars.GHCR_USER }} --password-stdin
    - name: Push the image into the container registry
      run: docker push ${REGISTRY_NAME}/${CONTAINER_NAME}:${CONTAINER_VERSION}
